name: build-test-publish
on:
  push:
    tags: ["v*"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Verify version matches tag
        run: |
          set -e
          PYVER=$(python -c "import tomllib, pathlib; print(tomllib.loads(pathlib.Path('pyproject.toml').read_text())['project']['version'])")
          TAG="${GITHUB_REF##*/}"; TAG="${TAG#v}"
          echo "Project version: $PYVER  Tag: $TAG"
          [ "$PYVER" = "$TAG" ] || { echo '::error::Tag v'"$TAG"' != version '"$PYVER"; exit 1; }

      - name: Build dists
        run: |
          python -m pip install --upgrade pip build
          rm -rf dist *.egg-info
          python -m build

      - name: Check metadata
        run: |
          python -m pip install --upgrade twine
          twine check dist/*

      - name: Publish (PyPI Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          verbose: true
          print-hash: true